# Dockerfile that will build a container that runs python with FastAPI and uvicorn on port 8080
FROM python:3.14@sha256:61346539f7b26521a230e72c11da5ebd872924745074b19736e7d65ba748c366
EXPOSE 8080
RUN apt update
RUN apt install -y libpq-dev
COPY requirements.txt /requirements.txt
RUN pip install --require-hashes -r /requirements.txt
COPY main.py /main.py
COPY main_sync.py /main_sync.py
COPY server.crt /server.crt
COPY server.key /server.key
CMD ["uvicorn", "--port", "8080", "--host", "0.0.0.0", "main:app"]
